export function Carts(){
   const MAZO = [
        { valor: 1, palo: 'espadas', jerarquia: 1, src:'./mazo/1-espadas.webp'},
        { valor: 2, palo: 'espadas', jerarquia: 6, src:'./mazo/2-espadas.webp' },
        { valor: 3, palo: 'espadas', jerarquia: 5, src:'./mazo/3-espadas.webp'},
        { valor: 4, palo: 'espadas', jerarquia: 14 ,src:'./mazo/4-espadas.webp'},
        { valor: 5, palo: 'espadas', jerarquia: 13 ,src:'./mazo/5-espadas.webp'},
        { valor: 6, palo: 'espadas', jerarquia: 12 ,src:'./mazo/6-espadas.webp'},
        { valor: 7, palo: 'espadas', jerarquia: 3 ,src:'./mazo/7-espadas.webp'},
        { valor: 10, palo: 'espadas', jerarquia: 10 ,src:'./mazo/10-espadas.webp'},
        { valor: 11, palo: 'espadas', jerarquia: 9 ,src:'./mazo/11-espadas.webp'},
        { valor: 12, palo: 'espadas', jerarquia: 8 ,src:'./mazo/12-espadas.webp'},
        { valor: 1, palo: 'basto', jerarquia: 2, src:'./mazo/1-basto.webp'},
        { valor: 2, palo: 'basto', jerarquia: 6, src:'./mazo/2-basto.webp' },
        { valor: 3, palo: 'basto', jerarquia: 5, src:'./mazo/3-basto.webp'},
        { valor: 4, palo: 'basto', jerarquia: 14, src:'./mazo/4-basto.webp' },
        { valor: 5, palo: 'basto', jerarquia: 13, src:'./mazo/5-basto.webp' },
        { valor: 6, palo: 'basto', jerarquia: 12, src:'./mazo/6-basto.webp' },
        { valor: 7, palo: 'basto', jerarquia: 11, src:'./mazo/7-basto.webp' },
        { valor: 10, palo: 'basto', jerarquia: 10, src:'./mazo/10-basto.webp' },
        { valor: 11, palo: 'basto', jerarquia: 9, src:'./mazo/11-basto.webp' },
        { valor: 12, palo: 'basto', jerarquia: 8 , src:'./mazo/12-basto.webp'},
        { valor: 1, palo: 'oro', jerarquia: 7, src:'./mazo/1-oro.webp'},
        { valor: 2, palo: 'oro', jerarquia: 6 , src:'./mazo/2-oro.webp'},
        { valor: 3, palo: 'oro', jerarquia: 5, src:'./mazo/3-oro.webp'},
        { valor: 4, palo: 'oro', jerarquia: 14, src:'./mazo/4-oro.webp' },
        { valor: 5, palo: 'oro', jerarquia: 13, src:'./mazo/5-oro.webp' },
        { valor: 6, palo: 'oro', jerarquia: 12, src:'./mazo/6-oro.webp' },
        { valor: 7, palo: 'oro', jerarquia: 4, src:'./mazo/7-oro.webp' },
        { valor: 10, palo: 'oro', jerarquia: 10, src:'./mazo/10-oro.webp' },
        { valor: 11, palo: 'oro', jerarquia: 9, src:'./mazo/11-oro.webp' },
        { valor: 12, palo: 'oro', jerarquia: 8, src:'./mazo/12-oro.webp' },
        { valor: 1, palo: 'copa', jerarquia: 7, src:'./mazo/1-copa.webp' },
        { valor: 2, palo: 'copa', jerarquia: 6, src:'./mazo/2-copa.webp' },
        { valor: 3, palo: 'copa', jerarquia: 5, src:'./mazo/3-copa.webp'},
        { valor: 4, palo: 'copa', jerarquia: 14, src:'./mazo/4-copa.webp' },
        { valor: 5, palo: 'copa', jerarquia: 13, src:'./mazo/5-copa.webp' },
        { valor: 6, palo: 'copa', jerarquia: 12, src:'./mazo/6-copa.webp' },
        { valor: 7, palo: 'copa', jerarquia: 11, src:'./mazo/7-copa.webp' },
        { valor: 10, palo: 'copa', jerarquia: 10, src:'./mazo/10-copa.webp' },
        { valor: 11, palo: 'copa', jerarquia: 9, src:'./mazo/11-copa.webp' },
        { valor: 12, palo: 'copa', jerarquia: 8, src:'./mazo/12-copa.webp' },
        
      ]

      return{MAZO}
}