export function Carts(){
   const MAZO = [
        { valor: 1, palo: 'espadas', jerarquia: 1 },
        { valor: 2, palo: 'espadas', jerarquia: 6 },
        { valor: 3, palo: 'espadas', jerarquia: 5},
        { valor: 4, palo: 'espadas', jerarquia: 14 },
        { valor: 5, palo: 'espadas', jerarquia: 13 },
        { valor: 6, palo: 'espadas', jerarquia: 12 },
        { valor: 7, palo: 'espadas', jerarquia: 3 },
        { valor: 10, palo: 'espadas', jerarquia: 10 },
        { valor: 11, palo: 'espadas', jerarquia: 9 },
        { valor: 12, palo: 'espadas', jerarquia: 8 },
        { valor: 1, palo: 'basto', jerarquia: 2 },
        { valor: 2, palo: 'basto', jerarquia: 6 },
        { valor: 3, palo: 'basto', jerarquia: 5},
        { valor: 4, palo: 'basto', jerarquia: 14 },
        { valor: 5, palo: 'basto', jerarquia: 13 },
        { valor: 6, palo: 'basto', jerarquia: 12 },
        { valor: 7, palo: 'basto', jerarquia: 11 },
        { valor: 10, palo: 'basto', jerarquia: 10 },
        { valor: 11, palo: 'basto', jerarquia: 9 },
        { valor: 12, palo: 'basto', jerarquia: 8 },
        { valor: 1, palo: 'oro', jerarquia: 7 },
        { valor: 2, palo: 'oro', jerarquia: 6 },
        { valor: 3, palo: 'oro', jerarquia: 5},
        { valor: 4, palo: 'oro', jerarquia: 14 },
        { valor: 5, palo: 'oro', jerarquia: 13 },
        { valor: 6, palo: 'oro', jerarquia: 12 },
        { valor: 7, palo: 'oro', jerarquia: 4 },
        { valor: 10, palo: 'oro', jerarquia: 10 },
        { valor: 11, palo: 'oro', jerarquia: 9 },
        { valor: 12, palo: 'oro', jerarquia: 8 },
        { valor: 1, palo: 'copa', jerarquia: 7 },
        { valor: 2, palo: 'copa', jerarquia: 6 },
        { valor: 3, palo: 'copa', jerarquia: 5},
        { valor: 4, palo: 'copa', jerarquia: 14 },
        { valor: 5, palo: 'copa', jerarquia: 13 },
        { valor: 6, palo: 'copa', jerarquia: 12 },
        { valor: 7, palo: 'copa', jerarquia: 11 },
        { valor: 10, palo: 'copa', jerarquia: 10 },
        { valor: 11, palo: 'copa', jerarquia: 9 },
        { valor: 12, palo: 'copa', jerarquia: 8 },
        
      ]

      return{MAZO}
}