export function Carts(){
   const MAZO = [
        { valor: 1, palo: 'espadas', jerarquia: 1, src:'./mazo/1-espada.png'},
        { valor: 2, palo: 'espadas', jerarquia: 6, src:'./mazo/2-espada.png' },
        { valor: 3, palo: 'espadas', jerarquia: 5, src:'./mazo/3-espada.png'},
        { valor: 4, palo: 'espadas', jerarquia: 14 ,src:'./mazo/4-espada.png'},
        { valor: 5, palo: 'espadas', jerarquia: 13 ,src:'./mazo/5-espada.png'},
        { valor: 6, palo: 'espadas', jerarquia: 12 ,src:'./mazo/6-espada.png'},
        { valor: 7, palo: 'espadas', jerarquia: 3 ,src:'./mazo/7-espada.png'},
        { valor: 10, palo: 'espadas', jerarquia: 10 ,src:'./mazo/10-espada.png'},
        { valor: 11, palo: 'espadas', jerarquia: 9 ,src:'./mazo/11-espada.png'},
        { valor: 12, palo: 'espadas', jerarquia: 8 ,src:'./mazo/12-espada.png'},
        { valor: 1, palo: 'basto', jerarquia: 2, src:'./mazo/1-basto.png'},
        { valor: 2, palo: 'basto', jerarquia: 6, src:'./mazo/2-basto.png' },
        { valor: 3, palo: 'basto', jerarquia: 5, src:'./mazo/3-basto.png'},
        { valor: 4, palo: 'basto', jerarquia: 14, src:'./mazo/4-basto.png' },
        { valor: 5, palo: 'basto', jerarquia: 13, src:'./mazo/5-basto.png' },
        { valor: 6, palo: 'basto', jerarquia: 12, src:'./mazo/6-basto.png' },
        { valor: 7, palo: 'basto', jerarquia: 11, src:'./mazo/7-basto.png' },
        { valor: 10, palo: 'basto', jerarquia: 10, src:'./mazo/10-basto.png' },
        { valor: 11, palo: 'basto', jerarquia: 9, src:'./mazo/11-basto.png' },
        { valor: 12, palo: 'basto', jerarquia: 8 , src:'./mazo/12-basto.png'},
        { valor: 1, palo: 'oro', jerarquia: 7, src:'./mazo/1-oro.png'},
        { valor: 2, palo: 'oro', jerarquia: 6 , src:'./mazo/2-oro.png'},
        { valor: 3, palo: 'oro', jerarquia: 5, src:'./mazo/3-oro.png'},
        { valor: 4, palo: 'oro', jerarquia: 14, src:'./mazo/4-oro.png' },
        { valor: 5, palo: 'oro', jerarquia: 13, src:'./mazo/5-oro.png' },
        { valor: 6, palo: 'oro', jerarquia: 12, src:'./mazo/6-oro.png' },
        { valor: 7, palo: 'oro', jerarquia: 4, src:'./mazo/7-oro.png' },
        { valor: 10, palo: 'oro', jerarquia: 10, src:'./mazo/10-oro.png' },
        { valor: 11, palo: 'oro', jerarquia: 9, src:'./mazo/11-oro.png' },
        { valor: 12, palo: 'oro', jerarquia: 8, src:'./mazo/12-oro.png' },
        { valor: 1, palo: 'copa', jerarquia: 7, src:'./mazo/1-copa.png' },
        { valor: 2, palo: 'copa', jerarquia: 6, src:'./mazo/2-copa.png' },
        { valor: 3, palo: 'copa', jerarquia: 5, src:'./mazo/3-copa.png'},
        { valor: 4, palo: 'copa', jerarquia: 14, src:'./mazo/4-copa.png' },
        { valor: 5, palo: 'copa', jerarquia: 13, src:'./mazo/5-copa.png' },
        { valor: 6, palo: 'copa', jerarquia: 12, src:'./mazo/6-copa.png' },
        { valor: 7, palo: 'copa', jerarquia: 11, src:'./mazo/7-copa.png' },
        { valor: 10, palo: 'copa', jerarquia: 10, src:'./mazo/10-copa.png' },
        { valor: 11, palo: 'copa', jerarquia: 9, src:'./mazo/11-copa.png' },
        { valor: 12, palo: 'copa', jerarquia: 8, src:'./mazo/12-copa.png' },
        
      ]

      return{MAZO}
}